language: c
script: asdf plugin-test dmd https://github.com/smashedtoatoms/asdf-dmd.git 
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
